name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t helloworld . --file Dockerfile --tag ghcr.io/dhabber/helloworld:$(date +%s) --tag ghcr.io/dhabber/helloworld:latest
    
    - name: Login
      run: echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Push the Docker Image
      run: docker push ghcr.io/dhabber/helloworld:latest  
      
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo docker kill helloworld || true
          sudo docker rm helloworld || true
          sudo docker pull ghcr.io/dhabber/helloworld:latest
          sudo docker run -d --name helloworld ghcr.io/dhabber/helloworld:latest
      
    
