name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t helloworld . --file Dockerfile --tag ghcr.io/dhabber/helloworld:$(date +%s) --tag ghcr.io/dhabber/helloworld:latest
    
    
  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      run: echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push the Docker Image
      run: docker push ghcr.io/dhabber/helloworld:latest
    
    
