name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t helloworld . --file Dockerfile --tag ghcr.io/dhabber/helloworld:$(date +%s)
    - name: Push the Docker image
      run: |
        docker login ghcr.io -u ${{ env.GITHUB_ACTOR }} -p ${{ secrets.GIT_TOKEN }}
        docker push ghcr.io/dhabber/helloworld:latest
